# The purpose of this workflow is to publish the workspace's crates
# whenever a tag is created. This basically boils down to running
# `scripts/publish.rs` at the right time.

on:
  push:
    tags:
      - "v*"

env:
  RUST_VERSION: 1.86

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required for OIDC token exchange (crates-io-auth-action)
    if: github.repository_owner == 'bytecodealliance/wac'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        shell: bash
        run: |
          rustup toolchain install ${{ env.RUST_VERSION }}
          rustup default ${{ env.RUST_VERSION }}

      - uses: rust-lang/crates-io-auth-action@v1.0.1
        id: auth

      - name: Publish wac crates to crates.io
        run: |
          rustc ci/publish.rs
          ./publish publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
